version: '3'

services:
  app:
    container_name: public-downscaling-cgan-app-${CONTAINER_NAME_SUFFIX}
    build:
      context: .
      dockerfile: Dockerfile.gpu
      args:
        - PIP_EXTRA_INDEX_URL
    tty: true
    volumes:
      - ./dsrnngan/:/app/dsrnngan
      - ./setup.py:/app/setup.py
      - ./setup.cfg:/app/setup.cfg
      - ./.vscode/:/app/.vscode
      - /mnt/RML-DC019/LiveData/Jupiter/2023/ERA5:/app/data/ERA5_raw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "$TENSORBOARD_PORT:${TENSORBOARD_PORT:-6006}"
      #- "$JUPYTER_PORT:$JUPYTER_PORT" # Uncomment if using Jupyter via a browser
    env_file:
     - ./.env
